## Deliverable 3. Create a Travel Itinerary Map.

In [2]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import gmaps.datasets

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [3]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("WeatherPy_vacation.csv")
vacation_df.head()

City_ID       City Country  Max Temp Current Description      Lat  \
0        2  Bathsheba      BB     79.41       broken clouds  13.2167   
1        3   Souillac      MU     81.36       broken clouds -20.5167   
2        5     Faanui      PF     80.76          light rain -16.4833   
3        6  Hithadhoo      MV     82.22       broken clouds  -0.6000   
4       11   West Bay      KY     83.07       broken clouds  19.3667   

        Lng                          Hotel Name  
0  -59.5167                      Atlantis Hotel  
1   57.5167         Shanti Maurice Resort & Spa  
2 -151.7500  Bora-Bora Pearl Beach Resort & Spa  
3   73.0833                   Scoop Guest House  
4  -81.4167                        Calypso Cove

In [4]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [5]:
# 4a. Add a marker layer for each city to the map.

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[(vacation_df["City"]=="Ilhabela")]
vacation_end = vacation_df.loc[(vacation_df["City"]=="Ilhabela")]
vacation_stop1 = vacation_df.loc[(vacation_df["City"]=="Arraial Do Cabo")]
vacation_stop2 = vacation_df.loc[(vacation_df["City"]=="Sao Joao Da Barra")]
vacation_stop3 = vacation_df.loc[(vacation_df["City"]=="Luziania")]

In [8]:
vacation_start

City_ID      City Country  Max Temp Current Description      Lat  \
139      509  Ilhabela      BR     75.52       broken clouds -23.7781   

         Lng       Hotel Name  
139 -45.3581  Ilha Flat Hotel

In [9]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start[["Lat","Lng"]].to_numpy()
end = vacation_end[["Lat","Lng"]].to_numpy()
stop1 = vacation_stop1[["Lat","Lng"]].to_numpy()
stop2 = vacation_stop2[["Lat","Lng"]].to_numpy()
stop3 = vacation_stop3[["Lat","Lng"]].to_numpy()

In [10]:
start,end,stop1,stop2,stop3

(array([[-23.7781, -45.3581]]),
 array([[-23.7781, -45.3581]]),
 array([[-22.9661, -42.0278]]),
 array([[-21.6403, -41.0511]]),
 array([[-16.2525, -47.9503]]))

In [11]:
start = (-23.7781, -45.3581)
end = (-23.7781, -45.3581)
stop1 = (-22.9661, -42.0278)
stop2 = (-21.6403, -41.0511)
stop3 = (-16.2525, -47.9503)

In [12]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

fig = gmaps.figure()
start2end_via_stop1_stop2_stop3 = gmaps.directions_layer(
        start, end, waypoints=[stop1,stop2,stop3],
        travel_mode='DRIVING')
fig.add_layer(start2end_via_stop1_stop2_stop3)
fig

Figure(layout=FigureLayout(height='420px'))

In [13]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start,vacation_end,vacation_stop1,vacation_stop2,vacation_stop3],ignore_index=True)
itinerary_df

City_ID               City Country  Max Temp Current Description      Lat  \
0      509           Ilhabela      BR     75.52       broken clouds -23.7781   
1      509           Ilhabela      BR     75.52       broken clouds -23.7781   
2      303    Arraial Do Cabo      BR     78.76          few clouds -22.9661   
3      123  Sao Joao Da Barra      BR     78.89           clear sky -21.6403   
4      296           Luziania      BR     78.49       broken clouds -16.2525   

       Lng               Hotel Name  
0 -45.3581          Ilha Flat Hotel  
1 -45.3581          Ilha Flat Hotel  
2 -42.0278      Pousada Porto Praia  
3 -41.0511  Pousada Porto De Canoas  
4 -47.9503              HOTEL SARON

In [14]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [15]:
# 11a. Add a marker layer for each city to the map.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))